### customize this file and save as DEBUG.toml

[LIBRARY]
### use the pip installed version of inkex.py, default: true
# prefer_pip_inkex = false

[LOGGING]
### logging configuration file, default: none - use implicit DEBUG logging to inkstitch.log
### we may have multiple configurations: LOGGING.toml, LOGGING1.toml, LOGGING2.toml, etc.
# log_config_file = "LOGGING.toml"

### disable globally logging: default: false - using logging.disable()
### reenable logging.disable(0)
# disable_logging = true

[DEBUG]
### simulate frozen mode, overwrite running_as_frozen in inkstitch.py, default: false
# force_frozen = true

### select one active debug_type, default: "none"
# debug_type = "vscode"
# debug_type = "pycharm"
# debug_type = "pydev"

### enable debugger, see cmd line arg -d, default: false
# debug_enable = true

### disable debugger when calling from inkscape, default: false
# disable_from_inkscape = true

### creation of bash script, default: false
# create_bash_script = true

### base name for bash script, default: "debug_inkstitch"
# bash_file_base = "debug_inkstitch"

### enable sew_stack elements, default: false
# enable_sew_stack = true

[PROFILE]
### select one active profiler_type, default: "none"
# profiler_type = "cprofile"
# profiler_type = "profile"
# profiler_type = "pyinstrument"
# profiler_type = "monkeytype"

### enable profiler, see cmd line arg -p, default: false
# profile_enable = true

### base name for profile output files, default: "debug_profile"
# profile_file_base = "logs/debug_profile"

